#!/usr/bin/env python3
"""Génère formulas_bank.js — référentiel formules PPL/LAPL (quantité + qualité)."""
import json
from pathlib import Path
from collections import Counter
from formula_enrich import enrich_all

ROOT = Path(__file__).parent
OUT = ROOT / "formulas_bank.js"


def F(**kw):
    """Helper formule avec défauts."""
    kw.setdefault("examples", [])
    kw.setdefault("worked", [])
    kw.setdefault("tags", [])
    kw.setdefault("prio", 2)
    return kw


# ═══════════════════════════════════════════════════════════
# BANQUE FORMULES — alignée examen PPL/LAPL (Aérogligli)
# prio: 3 = très fréquent examen · 2 = standard · 1 = rappel
# ═══════════════════════════════════════════════════════════
FORMULAS = [
    # ─── COMMUNICATIONS ───
    F(id="vhf-range", m="C", cat="Radio VHF", title="Portée radio VHF (propagation optique)",
      formula="D = 1,23 × √h", units="D en NM · h en pieds (ft)",
      vars=[{"s": "D", "d": "Distance de portée"}, {"s": "h", "d": "Hauteur antenne au-dessus du sol"}],
      explain="Formule la plus tombée en comm. Double la hauteur → portée ×1,41 (√2). Propagation ligne de vue uniquement.",
      mnemonic="√100=10 → 12,3 NM à 100 ft · √1000≈31,6 → 38,9 NM à 1000 ft",
      examples=["50 ft → 8,7 NM", "100 ft → 12,3 NM", "1000 ft → 38,9 NM", "2000 ft → 55,0 NM"],
      quizRef="Calcul portée VHF", calc="vhf", prio=3, tags=["calcul", "examen"]),
    F(id="vhf-range-2", m="C", cat="Radio VHF", title="Portée entre deux aéronefs",
      formula="D_tot ≈ 1,23 × (√h₁ + √h₂)", units="D_tot en NM · h₁, h₂ en ft",
      vars=[{"s": "h₁", "d": "Hauteur aéronef 1"}, {"s": "h₂", "d": "Hauteur aéronef 2"}],
      explain="Portée totale ≈ somme des portées individuelles depuis le sol. Communication air-air.",
      examples=["2 appareils à 1000 ft → ≈ 77,8 NM", "500 ft + 3000 ft → 1,23×(22,4+54,8) ≈ 95 NM"],
      quizRef="Calcul portée VHF", calc="vhf-2", prio=3, tags=["calcul"]),
    F(id="vhf-band", m="C", cat="Radio VHF", title="Bande de fréquences VHF aéronautique",
      formula="118,000 – 136,975 MHz", units="espacement 25 kHz (8,33 kHz en densité)",
      explain="Bande VHF COM aéronautique. Au sol : écoute 121,500 MHz (urgence) recommandée.",
      examples=["Tour : 118,100 MHz", "Approche : 119,700 MHz", "Urgence : 121,500 MHz"],
      quizRef="Bandes VHF", prio=3, tags=["constante"]),
    F(id="vhf-wavelength", m="C", cat="Radio VHF", title="Longueur d'onde VHF",
      formula="λ = c / f  ·  c ≈ 3×10⁸ m/s", units="f en Hz",
      explain="VHF = Very High Frequency. Propagation quasi-optique, pas de rebond ionosphérique fiable pour l'aéronautique.",
      examples=["118 MHz → λ ≈ 2,54 m", "136 MHz → λ ≈ 2,21 m"],
      quizRef="Bandes VHF", prio=2),
    F(id="vhf-urgency", m="C", cat="Fréquences", title="Fréquences d'urgence et détresse",
      formula="121,500 MHz · 243,0 MHz (militaire) · 406 MHz (COSPAS-SARSAT)", units="",
      explain="121,5 = urgence aéronautique internationale. 7700 transpondeur = détresse.",
      examples=["7600 = panne radio", "7700 = détresse", "7000 = VFR sans plan de vol"],
      quizRef="Fréquences particulières", prio=3, tags=["examen"]),
    F(id="radio-horizon", m="C", cat="Radio VHF", title="Horizon radio vs horizon optique",
      formula="Horizon radio ≈ 1,23 × horizon optique (approx.)", units="",
      explain="L'horizon radio est légèrement plus lointain que l'horizon visuel grâce à la réfraction atmosphérique.",
      quizRef="Calcul portée VHF", prio=2),
    F(id="squawk-codes", m="C", cat="Transpondeur", title="Codes transpondeur courants",
      formula="7000 VFR · 7600 panne radio · 7700 détresse · 2000 vol IFR sans assignation",
      units="Mode A/C/S",
      explain="Codes SSR à connaître par cœur. Confirmer avec ATC après changement sauf urgence.",
      quizRef="Fréquences particulières", prio=3, tags=["examen"]),
    F(id="ssr-principle", m="C", cat="Transpondeur", title="SSR — Secondary Surveillance Radar",
      formula="Interrogation sol → réponse transpondeur (code + altitude Mode C)", units="",
      explain="Permet identification et séparation ATC. Mode S : adresse unique avion.",
      quizRef="Contact radio", prio=2),
    F(id="readback-rule", m="C", cat="Phraséologie", title="Règle de read-back",
      formula="Read-back obligatoire : QNH · autorisation piste · niveau · cap · squawk · holding", units="",
      explain="Tout élément critique doit être répété. « Roger » seul insuffisant pour une autorisation.",
      quizRef="Phraséologie", prio=2),
    F(id="q-codes", m="C", cat="Phraséologie", title="Q-codes essentiels",
      formula="QNH · QFE · QTE · QDR · QDM · QTE", units="",
      explain="QNH = calage mer · QFE = calage terrain · QTE = cap vrai vers · QDR = cap vrai depuis station.",
      examples=["QNH 1013 → altimètre donne altitude", "QFE aérodrome → zéro au sol"],
      quizRef="Notions d'altimétrie", prio=3),
    F(id="phonetic-time", m="C", cat="Phraséologie", title="Annonce de l'heure en radio",
      formula="Heure UTC · 4 chiffres · chaque chiffre phonétique", units="",
      explain="Ex : 09h07 Z → « zero niner zero seven ». Toujours UTC en aviation.",
      quizRef="Phraséologie", prio=1),
    F(id="light-gun", m="C", cat="Signaux", title="Signaux lumineux au sol (rappel)",
      formula="Vert = autorisé · Rouge = stop · Blanc clignotant = reprenez position", units="",
      explain="En panne radio : acquitter par mouvement ailes ou roues selon sol/air.",
      quizRef="Signaux lumineux", prio=2),

    # ─── MÉTÉOROLOGIE ───
    F(id="isa-temp", m="M", cat="ISA", title="Température ISA",
      formula="T_ISA = 15 − 2 × (h / 1000)", units="T en °C · h en ft",
      vars=[{"s": "15", "d": "T° au niveau de la mer ISA"}, {"s": "2", "d": "Décroissance °C / 1000 ft"}],
      explain="Jusqu'à la tropopause (~36 000 ft). Chaque tranche de 1000 ft → −2°C.",
      mnemonic="15 au sol, −2 par mille",
      examples=["0 ft → +15°C", "5000 ft → +5°C", "10000 ft → −5°C", "36000 ft → tropopause"],
      quizRef="ISA - calcul T°", calc="isa-temp", prio=3, tags=["calcul", "examen"]),
    F(id="isa-delta", m="M", cat="ISA", title="Écart ISA (delta ISA)",
      formula="ISA ±n = T_réelle − T_ISA", units="n en °C",
      vars=[{"s": "+", "d": "Plus chaud que la normale"}, {"s": "−", "d": "Plus froid que la normale"}],
      explain="Compare la température observée à la température standard à la même altitude.",
      examples=["Sol +10°C, ISA +15°C → ISA −5", "1000 ft +18°C, ISA +13°C → ISA +5"],
      quizRef="ISA - delta", calc="isa-delta", prio=3, tags=["calcul"]),
    F(id="isa-pressure", m="M", cat="ISA", title="Pression ISA au niveau de la mer",
      formula="P₀ = 1013,25 hPa", units="hectopascals",
      explain="Référence standard. Calage 1013,25 hPa = altitude pression (PA / FL).",
      examples=["QNH = pression au niveau mer", "1013,25 = standard"],
      quizRef="Atmosphère type ISA", prio=3),
    F(id="isa-tropopause", m="M", cat="ISA", title="Tropopause ISA",
      formula="≈ 36 000 ft · T ≈ −56,5°C", units="",
      explain="Au-delà : stratosphère, température quasi constante.",
      quizRef="Atmosphère type ISA", prio=2),
    F(id="lapse-isa", m="M", cat="ISA", title="Décroissance ISA (lapse rate)",
      formula="−2°C / 1000 ft", units="jusqu'à 36 000 ft",
      explain="Identique à T_ISA. Ne pas confondre avec gradient adiabatique sec (3°C/1000).",
      quizRef="ISA - température", prio=3),
    F(id="press-gradient", m="M", cat="Pression", title="Gradients de pression ISA",
      formula="Δh par 1 hPa (varie avec l'altitude)", units="ft / hPa",
      explain="Plus on monte, plus il faut de feet pour 1 hPa — air moins dense.",
      examples=["0 ft → 28 ft/hPa", "5000 ft → 30 ft/hPa", "10000 ft → 37 ft/hPa", "18000 ft → 50 ft/hPa"],
      quizRef="Pression - gradients", calc="press-gradient", prio=3, tags=["calcul"]),
    F(id="pressure-alt", m="M", cat="Pression", title="Altitude pression (PA)",
      formula="PA = altitude lue avec QNH 1013,25 hPa", units="ft",
      explain="FL100 = PA 10 000 ft en conditions ISA. Différence QNH/1013 convertie en ft via gradient.",
      quizRef="Pression - altitude", prio=3),
    F(id="qnh-pa-diff", m="M", cat="Pression", title="Écart altitude QNH vs 1013",
      formula="Δh ≈ (1013 − QNH) × gradient ft/hPa", units="ft",
      explain="QNH < 1013 → altimètre calé 1013 lit plus haut que l'altitude vraie QNH.",
      examples=["QNH 1000 → ≈ 13×30 = 390 ft d'écart vs PA"],
      quizRef="Pression - altitude", calc="qnh-pa", prio=2, tags=["calcul"]),
    F(id="adiabat-sec", m="M", cat="Stabilité", title="Gradient adiabatique sec",
      formula="Γ_sec = 3°C / 1000 ft", units="°C par 1000 ft",
      explain="Parcelle d'air sec qui monte se refroidit de 3°C/1000 ft. Atmosphère >3°/1000 → instable.",
      examples=["4°C/1000 ft → instable", "3°C/1000 ft → neutre"],
      quizRef="Stabilité - adiabatiques", prio=3),
    F(id="adiabat-sat", m="M", cat="Stabilité", title="Gradient adiabatique saturé",
      formula="Γ_sat ≈ 1,5°C / 1000 ft", units="°C par 1000 ft",
      explain="Air humide saturé — libère chaleur latente en condensant, se refroidit moins vite.",
      quizRef="Stabilité - adiabatiques", prio=3),
    F(id="stability-rule", m="M", cat="Stabilité", title="Critère de stabilité (rappel)",
      formula="Environnement vs adiabatique sec", units="",
      explain="Env. < 3°/1000 → stable · Env. = 3° → neutre · Env. > 3° → instable (sec).",
      quizRef="Stabilité atmosphérique", prio=2),
    F(id="buys-ballot", m="M", cat="Vent", title="Règle de Buys-Ballot (Hém. N)",
      formula="Dos au vent → dépression à gauche · Hauteur à droite", units="",
      explain="Localise H et A. Vent geostrophique décalé ~15° vers basses pressions.",
      quizRef="Vent - Buys-Ballot", prio=3, tags=["examen"]),
    F(id="coriolis", m="M", cat="Vent", title="Force de Coriolis",
      formula="Dévie le vent vers la droite (Hém. N) · ∝ sin(latitude)", units="",
      explain="Rotation des dépressions anti-horaire (Hém. N). Plus fort aux latitudes élevées.",
      quizRef="Vent - Coriolis", prio=2),
    F(id="wind-back", m="M", cat="Vent", title="Vent de dos à l'altitude",
      formula="Vent au sol < vent en altitude (généralement)", units="",
      explain="Friction au sol ralentit le vent. Backing veering selon couche et fronts.",
      quizRef="Vent au sol vs altitude", prio=2),
    F(id="dew-spread", m="M", cat="Humidité", title="Écart température / point de rosée",
      formula="T − T_rosée = écart de saturation", units="°C",
      explain="Écart < 3°C → brume/brouillard probable. Écart grand → air sec.",
      quizRef="Température - point de rosée", prio=3),
    F(id="humidity-rate", m="M", cat="Humidité", title="Taux d'humidité relative",
      formula="HR = (Pv / Pvs) × 100", units="%",
      explain="Pv = pression vapeur réelle · Pvs = pression vapeur saturante à T donnée.",
      quizRef="Température - point de rosée", prio=2),
    F(id="visibility-cloud", m="M", cat="Nuages", title="Base nuage (approximation)",
      formula="Base (ft) ≈ (T − T_rosée) × 400", units="",
      explain="Règle empirique : écart T/rosée × 400 ≈ base cumulus en ft.",
      quizRef="Classification nuages", calc="cloud-base", prio=3, tags=["calcul"]),
    F(id="cloud-layers", m="M", cat="Nuages", title="Étages nuageux",
      formula="Bas < 2000 ft · Moyen 2000–7000 ft · Haut > 7000 ft", units="",
      explain="Classification par base. CB = enseignement vertical, éviter.",
      quizRef="Classification nuages", prio=2),
    F(id="front-cold-slope", m="M", cat="Fronts", title="Front froid — pente",
      formula="Pente ~ 1/50 à 1/100 · rapide", units="",
      explain="Front froid actif : temps violent, amélioration rapide après passage.",
      quizRef="Front froid - paramètres", prio=2),
    F(id="front-warm-slope", m="M", cat="Fronts", title="Front chaud — pente",
      formula="Pente ~ 1/150 à 1/300 · lent", units="",
      explain="Nimbus stratiformis, grisaille prolongée, amélioration lente.",
      quizRef="Front chaud - paramètres", prio=2),
    F(id="front-occluded", m="M", cat="Fronts", title="Front occlus",
      formula="Front froid rattrape front chaud", units="",
      explain="Système mature, temps dégradé complexe.",
      quizRef="Front occlus - paramètres", prio=1),
    F(id="metar-visibility", m="M", cat="METAR", title="Visibilité METAR",
      formula="9999 = ≥ 10 km · CAVOK = vis ≥10 km, pas nuage sous 5000 ft, pas phen", units="",
      explain="Visibilité en mètres. 1500 m minimum espace A VFR France.",
      quizRef="METAR - visibilité", prio=3),
    F(id="metar-wind", m="M", cat="METAR", title="Vent METAR",
      formula="dddffKT · ddd = cap vent (de) · ff = vitesse kt", units="",
      examples=["24015KT = vent de 240° à 15 kt", "VRB03KT = variable 3 kt"],
      quizRef="METAR - vent", prio=2),
    F(id="metar-qnh", m="M", cat="METAR", title="QNH dans METAR",
      formula="Q1013 · Q0998 etc.", units="hPa",
      explain="Toujours vérifier QNH avant vol. Écart important = correction altimétrique significative.",
      quizRef="METAR - QNH", prio=3),
    F(id="taf-validity", m="M", cat="TAF", title="Validité TAF",
      formula="Format DDHH/DDHH · PROB · TEMPO · BECMG", units="UTC",
      explain="TAF = prévision aérodrome. PROB40/30 = probabilité phénomène.",
      quizRef="TAF - validité", prio=2),
    F(id="icing-temp", m="M", cat="Givrage", title="Givrage — températures critiques",
      formula="Givrage sévère : −10°C à 0°C · carburation : 0°C à 20°C", units="",
      explain="Carburation plus fréquente entre −7°C et +21°C avec humidité.",
      quizRef="Perturbations", prio=2),
    F(id="freezing-level", m="M", cat="Givrage", title="Isotherme 0°C",
      formula="Monte avec air chaud · Descend avec air froid", units="",
      explain="Sous 0°C : risque de givrage en vol visible. Surveiller METAR/TAF.",
      quizRef="Perturbations", prio=2),
    F(id="density-alt-concept", m="M", cat="Performance météo", title="Altitude densité (concept)",
      formula="Air chaud/humide/bas pression → altitude densité ↑ → performances ↓", units="",
      explain="Même altimètre, moins de masse d'air → distance décollage augmentée.",
      quizRef="T° et altimètre", prio=2),
    F(id="pressure-tendency", m="M", cat="Pression", title="Tendance barométrique",
      formula="Basse pression → mauvais temps · Haute → beau temps (Hém. N)", units="",
      explain="Rapide chute = dégradation imminente. Stabilisation après front.",
      quizRef="Pression - variations", prio=2),

    # ─── AÉRONEF ───
    F(id="vp-calc", m="A", cat="Vitesses", title="Vitesse propre (Vp / TAS)",
      formula="Vp = Vi × (1 + FL×10÷6 %) × (1 + |ΔT|÷4 %)", units="Vi et Vp en kt",
      vars=[{"s": "FL×10÷6", "d": "Correction altitude (%)"}, {"s": "|ΔT|÷4", "d": "+1% par 4°C d'écart"}],
      explain="Formule officielle banque examen Aérogligli.",
      mnemonic="FL010 → +16% · chaque 4°C → +1%",
      examples=["Vi=100 FL010, ΔT=16°C → 121 kt", "Vi=103 FL011, ΔT=12°C → 125 kt"],
      quizRef="Calcul Vp", calc="vp", prio=3, tags=["calcul", "examen"]),
    F(id="speed-types", m="A", cat="Vitesses", title="Vitesses aéronautiques",
      formula="Vi · Vp/TAS · GS · CAS · IAS", units="",
      explain="Vi = indicatrice · Vp = vraie (TAS) · GS = sol · CAS corrigée compressibilité.",
      quizRef="Calcul Vp", prio=3),
    F(id="vspeeds", m="A", cat="Vitesses", title="Vitesses de référence (mémo)",
      formula="Vs0 · Vs1 · VFE · VLE · VNO · VNE · VA", units="kt CAS",
      explain="Vs0=stall config · Vs1=clean · VFE=volets · VLE=train · VNO=turbulence · VNE=never exceed · VA=manœuvre.",
      quizRef="Vitesses caractéristiques", prio=3),
    F(id="load-factor", m="A", cat="Performances", title="Facteur de charge en virage",
      formula="n = 1 / cos(bank)", units="bank en degrés",
      explain="Virage 60° → n = 2. Va diminue avec masse et avec n.",
      examples=["30° → n ≈ 1,15", "45° → n ≈ 1,41", "60° → n = 2"],
      quizRef="Facteur de charge", calc="load-factor", prio=3, tags=["calcul"]),
    F(id="stall-load", m="A", cat="Performances", title="Vitesse de décrochage vs charge",
      formula="Vs = Vs1 × √n", units="kt",
      explain="Facteur charge double → Vs augmente de √2 ≈ 41%.",
      examples=["n=2 → Vs × 1,41", "n=1,44 → Vs × 1,2"],
      quizRef="Facteur de charge", calc="stall-n", prio=3, tags=["calcul"]),
    F(id="turn-rate", m="A", cat="Navigation", title="Taux de virage standard",
      formula="3°/s · 360° en 2 min (Rate 1)", units="",
      explain="Virage standard IFR. Taux ∝ tan(bank) × V / V.",
      quizRef="Coordinateur de virage", prio=2),
    F(id="alt-temp-corr", m="A", cat="Altimètre", title="Correction altimétrique (température)",
      formula="Δh = 4 × (h/1000) × (T − T_std)", units="Δh en ft",
      vars=[{"s": "T > T_std", "d": "Air chaud → altimètre sous-estime"}, {"s": "T < T_std", "d": "Air froid → altimètre surestime"}],
      explain="Altitude réelle = altitude lue ± correction selon signe.",
      mnemonic="4 × mille × écart T",
      examples=["2000 ft, T=+26°C, std=+11°C → réelle 2120 ft", "1000 ft, T=−5°C, std=+13°C → réelle 928 ft"],
      quizRef="Correction altimétrique T°", calc="alt-corr", prio=3, tags=["calcul", "examen"]),
    F(id="alt-gradient", m="A", cat="Altimètre", title="Gradient altimétrique standard",
      formula="≈ 27 ft / hPa (standard) · 30 ft / hPa (approximation)", units="",
      explain="Chaque hPa QNH ↔ 1013 ≈ 27–30 ft. Erreur 25 ft/hPa → surestimation.",
      quizRef="Altimètre - gradient", prio=3),
    F(id="qnh-qfe", m="A", cat="Altimètre", title="Calages altimétriques",
      formula="QNH → altitude · QFE → hauteur · 1013,25 → PA/FL", units="",
      explain="QNH : calage mer. QFE : zéro au sol. 1013,25 : altitude pression.",
      quizRef="Calages altimétriques", prio=3, tags=["examen"]),
    F(id="true-alt-qnh", m="A", cat="Altimètre", title="Altitude vraie depuis QNH",
      formula="Alt vraie ≈ alt lue + (QNH − 1013) × gradient", units="ft",
      explain="QNH > 1013 → vraie > lue. Inverse pour QNH bas.",
      quizRef="Notions d'altimétrie", calc="true-alt", prio=2, tags=["calcul"]),
    F(id="kt-kmh", m="A", cat="Conversions", title="Nœuds → km/h (rapide)",
      formula="km/h ≈ kt × 2 − 10%", units="",
      explain="Astuce mentale examen. 100 kt → 180 km/h.",
      examples=["100 kt → 180 km/h", "120 kt → 216 km/h"],
      quizRef="Conversion kt/km/h", calc="kt-kmh", prio=3),
    F(id="kt-kmh-exact", m="A", cat="Conversions", title="Nœuds → km/h (exact)",
      formula="km/h = kt × 1,852", units="",
      examples=["100 kt = 185,2 km/h"],
      quizRef="Conversion kt/km/h", prio=2),
    F(id="kmh-kt", m="A", cat="Conversions", title="km/h → Nœuds",
      formula="kt = km/h ÷ 1,852", units="",
      examples=["180 km/h ≈ 97 kt"],
      quizRef="Conversion kt/km/h", calc="kmh-kt", prio=2),
    F(id="ms-ftmin", m="A", cat="Conversions", title="m/s → ft/min (variomètre)",
      formula="ft/min ≈ m/s × 200", units="",
      examples=["1 m/s ≈ 200 ft/min", "2,5 m/s ≈ 500 ft/min"],
      quizRef="Variomètre", calc="ms-ftmin", prio=2),
    F(id="descent-vz", m="A", cat="Performance", title="Taux de descente",
      formula="Vz (ft/min) = gradient (%) × Vsol (kt)", units="",
      explain="Pente 5% à 90 kt → Vz = 450 ft/min.",
      examples=["5% × 90 kt = 450 ft/min", "3% × 120 kt = 360 ft/min"],
      quizRef="Variomètre - astuce", calc="descent", prio=3, tags=["calcul"]),
    F(id="climb-gradient", m="A", cat="Performance", title="Gradient de montée",
      formula="Gradient (%) = (Vz / Vsol) × 100", units="",
      explain="Inverse de la descente. ROC en ft/min ÷ GS en kt × 100.",
      quizRef="Variomètre", prio=2),
    F(id="autonomy", m="A", cat="Performance", title="Autonomie carburant",
      formula="Autonomie = Carburant disponible / Débit horaire", units="heures",
      explain="Inclure réserve réglementaire (30 min VFR jour France).",
      examples=["60 L à 30 L/h → 2 h", "120 L à 40 L/h → 3 h (hors réserve)"],
      quizRef="Plan de vol - paramètres", calc="autonomy", prio=3, tags=["calcul"]),
    F(id="fuel-flow", m="A", cat="Performance", title="Consommation horaire",
      formula="Débit = Carburant / Temps de vol", units="L/h ou kg/h",
      examples=["45 L en 1h30 → 30 L/h"],
      quizRef="Plan de vol - paramètres", calc="fuel-flow", prio=2),
    F(id="distance-time", m="A", cat="Navigation", title="Distance – Temps – Vitesse",
      formula="D = V × T  ·  T = D / V  ·  V = D / T", units="D en NM · V en kt · T en h",
      examples=["120 kt × 1,5 h = 180 NM", "60 NM à 90 kt = 40 min"],
      calc="dist-time", prio=3, tags=["calcul"]),
    F(id="load-moment", m="A", cat="Masse & centrage", title="Moment de force (centraje)",
      formula="M = masse × bras de levier", units="kg·m",
      explain="CG = Σ moments / masse totale. Doit rester dans enveloppe.",
      examples=["100 kg à 2 m → 200 kg·m"],
      quizRef="Géométrie avion", prio=2),
    F(id="cg-limits", m="A", cat="Masse & centrage", title="Limites de centrage",
      formula="Enveloppe CG avant/arrière · masse max AUW", units="",
      explain="Hors limites = controllabilité compromise. Recalculer à chaque chargement.",
      quizRef="Géométrie avion", prio=2),
    F(id="lift-basic", m="A", cat="Aérodynamique", title="Portance (rappel)",
      formula="L = ½ ρ V² S CL", units="",
      explain="Portance ∝ vitesse². Double V → quadruple L (à CL constant).",
      quizRef="Géométrie avion", prio=2),
    F(id="drag-parasite", m="A", cat="Aérodynamique", title="Traînée parasite",
      formula="D_p ∝ V²", units="",
      explain="Domine à haute vitesse. Induite domine à basse vitesse.",
      quizRef="Géométrie avion", prio=1),
    F(id="crosswind", m="A", cat="Navigation sol", title="Composante vent de travers",
      formula="XWC = vent × sin(Δ cap)", units="kt",
      explain="Δ = angle entre piste et vent. Composante max dans AFM.",
      quizRef="Plan de vol", calc="crosswind", prio=2, tags=["calcul"]),
    F(id="headwind", m="A", cat="Navigation sol", title="Composante vent de face/arrière",
      formula="HWC = vent × cos(Δ cap)", units="kt",
      explain="Vent de face → GS réduit · arrière → GS augmenté.",
      calc="headwind", prio=2, tags=["calcul"]),
    F(id="fuel-weight", m="A", cat="Performance", title="Masse carburant",
      formula="Essence ≈ 0,72 kg/L · JET A1 ≈ 0,80 kg/L", units="",
      explain="Masse carburant compte dans CG et performances.",
      quizRef="Moteur - carburants", prio=2),
    F(id="carb-icing", m="A", cat="Moteur", title="Givrage carburateur",
      formula="Risque max ≈ −7°C à +21°C · humidité · gaz riches", units="",
      explain="Chauffage carbu ou injection directe réduit le risque.",
      quizRef="Moteur - carburants", prio=2),
    F(id="engine-cycle", m="A", cat="Moteur", title="Cycle 4 temps",
      formula="Admission · Compression · Explosion · Échappement", units="",
      explain="2 tours vilebrequin = 1 cycle. PMH = point mort haut.",
      quizRef="Cycle 4 temps", prio=2),
    F(id="prop-constant", m="A", cat="Hélice", title="Hélice à pas variable",
      formula="RPM constant · pas augmente → plus de portance/traînée", units="",
      explain="En montée : grand pas. En croisière : optimisé.",
      quizRef="Hélice à vitesse constante", prio=2),
    F(id="anemometer-block", m="A", cat="Instruments", title="Panne anémomètre bouché",
      formula="Vi → 0 · Vp/TAS estimée · altimètre et variomètre OK", units="",
      explain="Pitot bouché + drains OK → Vi fausse. Pitot+static bouchés → alti et Vi fausses.",
      quizRef="Pannes circuit anémométrique", prio=3),
    F(id="anemometer-leak", m="A", cat="Instruments", title="Panne anémomètre fuite static",
      formula="Vi et altimètre erronés · VSI transitoire", units="",
      explain="Trouver cause : chauffage pitot, circuit, condensats.",
      quizRef="Pannes circuit anémométrique", prio=2),

    # ─── RÉGLEMENTATION & NAVIGATION ───
    F(id="nm-km", m="R", cat="Conversions", title="Mille nautique ↔ kilomètre",
      formula="1 NM = 1,852 km  ·  1 km = 0,54 NM", units="",
      examples=["10 NM = 18,52 km", "50 km ≈ 27 NM"],
      calc="nm-km", prio=3, tags=["calcul"]),
    F(id="ft-m", m="R", cat="Conversions", title="Pieds ↔ mètres",
      formula="1 ft = 0,3048 m  ·  1 m = 3,281 ft", units="",
      examples=["1000 ft ≈ 305 m", "3000 m ≈ 9843 ft"],
      calc="ft-m", prio=2),
    F(id="mph-kt", m="R", cat="Conversions", title="Miles/h → nœuds",
      formula="kt ≈ mph × 0,87", units="",
      examples=["100 mph ≈ 87 kt"],
      prio=1),
    F(id="rule-60", m="R", cat="Navigation", title="Règle du 1:60",
      formula="Déviation (NM) ≈ (Distance NM / 60) × Angle (°)", units="",
      explain="À 60 NM, 1° ≈ 1 NM de décalage latéral.",
      mnemonic="60 NM → 1° = 1 NM",
      examples=["60 NM, 2° → 2 NM", "30 NM, 4° → 2 NM"],
      quizRef="Navigation - 1:60", calc="rule-60", prio=3, tags=["calcul", "examen"]),
    F(id="wind-triangle", m="R", cat="Navigation", title="Triangle des vitesses",
      formula="TAS + vent → GS · WCA · cap vrai", units="",
      explain="Vent de face GS<TAS · arrière GS>TAS · composante croisée → dérive.",
      examples=["Vent 20 kt face, TAS 100 → GS ≈ 80 kt"],
      quizRef="Plan de vol", prio=3),
    F(id="semi-circular", m="R", cat="Navigation", title="Règle semi-circulaire VFR",
      formula="Cap 000–179° → impairs×1000+500 · Cap 180–359° → pairs×1000+500", units="ft",
      explain="Cap 090° → FL35,55,75… · Cap 270° → FL45,65,85…",
      quizRef="Règle semi-circulaire", calc="semi-circular", prio=3, tags=["examen"]),
    F(id="semi-circular-ex", m="R", cat="Navigation", title="Exemples semi-circulaire",
      formula="Cap 045° → 3500, 5500 ft · Cap 225° → 4500, 6500 ft", units="",
      examples=["Cap 179° → 3500 ft OK", "Cap 180° → 4500 ft OK"],
      quizRef="Règle semi-circulaire", prio=2),
    F(id="exam-threshold", m="R", cat="Examen", title="Seuil examen théorique PPL",
      formula="75 % par épreuve · 64 questions · 9·15·20·20", units="",
      explain="C 9 · A 15 · M 20 · R 20. Pas de timer officiel France.",
      quizRef="Examen théorique", prio=3, tags=["examen"]),
    F(id="exam-modules", m="R", cat="Examen", title="Répartition modules examen",
      formula="C=9 · A=15 · M=20 · R=20 · Total=64", units="questions",
      quizRef="Examen théorique", prio=3),
    F(id="fuel-reserve-vfr", m="R", cat="Planification", title="Réserve carburant VFR (France)",
      formula="Utile ≥ vol + marge + réserve (30 min VFR jour)", units="",
      explain="Vérifier AIP / réglementation. Nuit ou IFR : règles différentes.",
      quizRef="Plan de vol - paramètres", prio=3),
    F(id="time-fuel", m="R", cat="Planification", title="Temps vers carburant",
      formula="Carburant = Débit × Temps (+ réserve + marge)", units="",
      explain="Arrondir au supérieur. Inclure montée/descente et vent.",
      quizRef="Plan de vol - paramètres", prio=2),
    F(id="visibility-min", m="R", cat="VFR", title="Visibilité minimale VFR (rappel)",
      formula="1500 m espace A · 5 km C/D · 8 km E (selon réglementation)", units="",
      explain="Seuils + distance nuages. Vérifier SERA / AIP France.",
      quizRef="Conditions VMC - EAC", prio=3),
    F(id="vmc-cloud-dist", m="R", cat="VFR", title="Distance aux nuages VFR",
      formula="Hors nuages · en vue du sol · distances selon espace aérien", units="",
      quizRef="Conditions VMC - EANC", prio=2),
    F(id="vfr-night", m="R", cat="VFR", title="VFR nuit — rappels",
      formula="Formation spécifique · double décollage · visibilité augmentée", units="",
      quizRef="VFR nuit - conditions météo", prio=2),
    F(id="vfr-special", m="R", cat="VFR", title="VFR spécial",
      formula="Demande pilote · acceptation ATC · visibilité ≥ 5 km", units="",
      quizRef="VFR spécial", prio=2),
    F(id="airspace-classes", m="R", cat="Espace aérien", title="Classes d'espace aérien (rappel)",
      formula="A IFR · B C D CTR · E TMA · F G", units="",
      explain="France : majoritairement E et G. CTR/CTA = autorisation.",
      quizRef="Espace aérien", prio=2),
    F(id="ctr-floor", m="R", cat="Espace aérien", title="CTR — contrôle",
      formula="Autorisation ATC obligatoire · transpondeur souvent requis", units="",
      quizRef="Espace aérien - CTR", prio=2),
    F(id="flight-plan-time", m="R", cat="Plan de vol", title="Dépôt plan de vol",
      formula="Au moins 60 min avant (IFR) · VFR selon AIP", units="",
      quizRef="Plan de vol", prio=2),
    F(id="medical-lapl", m="R", cat="Licences", title="Certificat médical LAPL",
      formula="Classe 2 LAPL · validité selon âge", units="",
      quizRef="Certificat médical LAPL", prio=2),
    F(id="lapl-privileges", m="R", cat="Licences", title="Privilèges LAPL(A)",
      formula="VFR · max 4 passagers · MTOM ≤ 2000 kg · non rémunéré", units="",
      quizRef="Licence LAPL - privilèges", prio=2),
    F(id="ppl-privileges", m="R", cat="Licences", title="Privilèges PPL(A)",
      formula="VFR · extension qualifications · base pour CPL/ATPL", units="",
      quizRef="Licence PPL", prio=2),
    F(id="sep-renewal", m="R", cat="Licences", title="Validité SEP — expérience",
      formula="12 h · 12 décollages/attero · 1h avec FI · exam prorogation", units="24 mois",
      quizRef="Prorogation SEP", prio=2),
    F(id="priority-rules", m="R", cat="Circulation", title="Priorités aériennes",
      formula="Ballon · planeur · parachute · ULM · montgolfière · avion", units="",
      explain="Règles détaillées SERA. Dernière ressource : manœuvre anti-collision.",
      quizRef="Règles de priorité", prio=2),
    F(id="right-of-way", m="R", cat="Circulation", title="Convergence même hauteur",
      formula="Voyant vert à droite → priorité à droite", units="",
      quizRef="Règles de priorité", prio=2),
    F(id="overtake-rule", m="R", cat="Circulation", title="Dépassement",
      formula="Dépasser par la droite · distance sécurité", units="",
      quizRef="Règles de priorité", prio=1),
    F(id="min-alt-vfr", m="R", cat="VFR", title="Hauteur minimale de survol",
      formula="300 m (1000 ft) au-dessus obstacles · exceptions survol", units="",
      quizRef="Hauteurs de survol", prio=2),
    F(id="transponder-vfr", m="R", cat="Équipements", title="Transpondeur VFR",
      formula="Obligatoire dans certains espaces · Mode C si équipé", units="",
      quizRef="Équipements réglementaires", prio=2),
    F(id="oxygen-requirement", m="R", cat="Équipements", title="Oxygène supplémentaire",
      formula="Selon altitude cabine · durée · pressurisation", units="",
      quizRef="Équipements - oxygène", prio=1),
    F(id="documents-board", m="R", cat="Licences", title="Documents à bord",
      formula="Certificat · qualifications · médical · masse/balance · POH", units="",
      quizRef="Licence PPL", prio=2),
    F(id="alcohol-limit", m="R", cat="Licences", title="Alcoolémie (rappel)",
      formula="0,20 g/L sang (≈ 0,25 mg/L air) pour pilote", units="",
      quizRef="Licence PPL", prio=2),
    F(id="intercept-signals", m="R", cat="Signaux", title="Signaux d'interception",
      formula="Oscillations ailes = suivez · balancement = quitter zone", units="",
      quizRef="Signaux d'interception", prio=2),
    F(id="ground-signals", m="R", cat="Signaux", title="Signaux au sol (placeur)",
      formula="T · L · C · barres direction · cône", units="",
      quizRef="Signaux placeur", prio=2),
    F(id="fir-uir", m="R", cat="Espace aérien", title="FIR / UIR",
      formula="FIR = Flight Information Region · UIR = Upper", units="",
      quizRef="Espace aérien - FIR", prio=1),
    F(id="temsi-scale", m="R", cat="Cartes", title="Échelles cartes TEMSI",
      formula="1:500 000 · 1:250 000 · 1:200 000", units="",
      quizRef="Cartes TEMSI", prio=2),
    F(id="wintem-use", m="R", cat="Cartes", title="Carte WINTEM",
      formula="Vent, température, tropopause en altitude", units="",
      quizRef="Cartes WINTEM", prio=2),
    F(id="eet-calc", m="R", cat="Plan de vol", title="Estimation temps de vol (EET)",
      formula="EET = distance / GS · + marge montée/descente", units="",
      quizRef="Plan de vol - paramètres", calc="dist-time", prio=2),
]

# Ajout formules dérivées qualité (tables ISA, portées VHF types)
ISA_ALTITUDES = [0, 500, 1000, 2000, 3000, 5000, 8000, 10000, 15000, 20000, 36000]
for alt in ISA_ALTITUDES:
    t = round(15 - 2 * (alt / 1000))
    if alt == 36000:
        t = -56
    FORMULAS.append(F(
        id=f"isa-table-{alt}", m="M", cat="ISA — tables", title=f"Température ISA à {alt} ft",
        formula=f"T_ISA = {t}°C", units="",
        explain=f"Valeur directe : 15 − 2×({alt}/1000) = {t}°C.",
        examples=[f"{alt} ft → {t}°C"],
        quizRef="ISA - calcul T°", prio=1, tags=["table"],
    ))

VHF_HEIGHTS = [25, 50, 100, 200, 500, 1000, 1500, 2000, 3000, 5000]
for h in VHF_HEIGHTS:
    d = round(1.23 * (h ** 0.5), 1)
    FORMULAS.append(F(
        id=f"vhf-table-{h}", m="C", cat="VHF — tables", title=f"Portée VHF à {h} ft",
        formula=f"D = {d} NM", units="",
        explain=f"1,23 × √{h} = {d} NM.",
        examples=[f"Antenne {h} ft → {d} NM"],
        quizRef="Calcul portée VHF", prio=1, tags=["table"],
    ))

PRESS_GRAD = [(0, 28), (2000, 29), (5000, 30), (8000, 34), (10000, 37), (15000, 43), (18000, 50), (25000, 60), (30000, 75)]
for alt, grad in PRESS_GRAD:
    FORMULAS.append(F(
        id=f"press-grad-{alt}", m="M", cat="Pression — tables", title=f"Gradient pression à {alt} ft",
        formula=f"≈ {grad} ft / hPa", units="",
        explain="Valeur ISA indicative pour conversion pression ↔ altitude.",
        quizRef="Pression - gradients", prio=1, tags=["table"],
    ))

LOAD_BANKS = [15, 20, 30, 45, 60, 75, 90]
for bank in LOAD_BANKS:
    import math
    n = round(1 / math.cos(math.radians(bank)), 2)
    FORMULAS.append(F(
        id=f"load-bank-{bank}", m="A", cat="Virage — tables", title=f"Facteur charge à {bank}°",
        formula=f"n = {n}", units="",
        explain=f"1 / cos({bank}°) = {n}.",
        examples=[f"Stall speed × {round(n**0.5, 2)} si n={n}"],
        quizRef="Facteur de charge", prio=1, tags=["table"],
    ))

FORMULA_KEYWORDS = [
    {"keys": ["vhf", "portée", "1,23", "propagation", "radio", "118", "136 mhz"], "ids": ["vhf-range", "vhf-range-2", "vhf-wavelength", "vhf-band", "radio-horizon"]},
    {"keys": ["121,5", "7600", "7700", "7000", "squawk", "transpondeur"], "ids": ["squawk-codes", "vhf-urgency", "ssr-principle"]},
    {"keys": ["read-back", "readback", "qnh", "qfe", "q-code"], "ids": ["readback-rule", "q-codes", "qnh-qfe"]},
    {"keys": ["isa", "atmosphère type", "tropopause", "1013"], "ids": ["isa-temp", "isa-delta", "isa-pressure", "lapse-isa", "press-gradient", "isa-tropopause"]},
    {"keys": ["température", "point de rosée", "rosée", "humidité", "brume"], "ids": ["dew-spread", "humidity-rate", "visibility-cloud"]},
    {"keys": ["adiabat", "stabilité", "instable"], "ids": ["adiabat-sec", "adiabat-sat", "stability-rule"]},
    {"keys": ["vent", "buys", "coriolis", "géostrophique"], "ids": ["buys-ballot", "coriolis", "wind-triangle", "wind-back"]},
    {"keys": ["metar", "taf", "cavok", "9999"], "ids": ["metar-visibility", "metar-wind", "metar-qnh", "taf-validity"]},
    {"keys": ["front froid", "front chaud", "occlus"], "ids": ["front-cold-slope", "front-warm-slope", "front-occluded"]},
    {"keys": ["vp", "vitesse propre", "vi=", "tas", "vi "], "ids": ["vp-calc", "speed-types", "vspeeds"]},
    {"keys": ["altimètre", "qnh", "qfe", "calage", "altitude réelle", "altitude pression"], "ids": ["alt-temp-corr", "alt-gradient", "qnh-qfe", "pressure-alt", "true-alt-qnh"]},
    {"keys": ["kt", "nœud", "km/h", "conversion"], "ids": ["kt-kmh", "kt-kmh-exact", "kmh-kt", "nm-km"]},
    {"keys": ["variomètre", "ft/min", "m/s", "descente", "montée"], "ids": ["ms-ftmin", "descent-vz", "climb-gradient"]},
    {"keys": ["carburant", "autonomie", "réserve", "plan de vol"], "ids": ["autonomy", "fuel-flow", "time-fuel", "fuel-reserve-vfr", "eet-calc"]},
    {"keys": ["centrage", "moment", "masse", "cg"], "ids": ["load-moment", "cg-limits"]},
    {"keys": ["virage", "facteur de charge", "inclinaison", "bank"], "ids": ["load-factor", "stall-load", "turn-rate"]},
    {"keys": ["1:60", "dérive", "navigation"], "ids": ["rule-60", "distance-time", "nm-km", "wind-triangle"]},
    {"keys": ["semi-circulaire", "niveau de vol", "fl3", "fl4"], "ids": ["semi-circular", "semi-circular-ex"]},
    {"keys": ["vfr", "visibilité", "espace a", "espace e", "vmc"], "ids": ["visibility-min", "vmc-cloud-dist", "vfr-night", "vfr-special"]},
    {"keys": ["examen", "75 %", "64 question"], "ids": ["exam-threshold", "exam-modules"]},
    {"keys": ["pitot", "anémomètre", "static", "panne"], "ids": ["anemometer-block", "anemometer-leak"]},
    {"keys": ["licence", "lapl", "ppl", "sep", "médical"], "ids": ["medical-lapl", "lapl-privileges", "ppl-privileges", "sep-renewal"]},
    {"keys": ["priorité", "convergence", "dépassement"], "ids": ["priority-rules", "right-of-way", "overtake-rule"]},
    {"keys": ["givrage", "carburation", "carbu"], "ids": ["icing-temp", "freezing-level", "carb-icing"]},
    {"keys": ["portance", "traînée", "aérodynamique"], "ids": ["lift-basic", "drag-parasite"]},
    {"keys": ["vent travers", "crosswind", "composante"], "ids": ["crosswind", "headwind"]},
]

MODULE_ESSENTIALS = {
    "C": [
        {"k": "Portée VHF", "v": "D = 1,23 × √h (NM)"},
        {"k": "Bande VHF", "v": "118 – 136 MHz"},
        {"k": "Urgence", "v": "121,500 MHz"},
        {"k": "Squawk", "v": "7600 radio · 7700 détresse · 7000 VFR"},
        {"k": "Propagation", "v": "Ligne de vue (optique)"},
        {"k": "2 appareils", "v": "1,23×(√h₁+√h₂)"},
    ],
    "M": [
        {"k": "ISA sol", "v": "+15°C · 1013,25 hPa"},
        {"k": "Décroissance", "v": "−2°C / 1000 ft"},
        {"k": "Tropopause", "v": "≈ 36 000 ft · −56,5°C"},
        {"k": "Adiabatique sec", "v": "3°C / 1000 ft"},
        {"k": "Adiabatique sat.", "v": "≈ 1,5°C / 1000 ft"},
        {"k": "Base nuage", "v": "(T − T_rosée) × 400 ft"},
        {"k": "Gradient pression", "v": "≈ 28–37 ft/hPa"},
        {"k": "Buys-Ballot", "v": "Dos au vent → dépression à gauche"},
    ],
    "A": [
        {"k": "Vp (examen)", "v": "Vi×(1+FL×10÷6%)×(1+|ΔT|÷4%)"},
        {"k": "Correction T° alti", "v": "4×(h/1000)×|ΔT| ft"},
        {"k": "Gradient alti", "v": "≈ 27 ft/hPa"},
        {"k": "QNH / QFE / PA", "v": "Alt · Hauteur · FL"},
        {"k": "kt → km/h", "v": "×1,852 · astuce ×2−10%"},
        {"k": "Facteur charge", "v": "n = 1/cos(bank)"},
        {"k": "Vs avec n", "v": "Vs = Vs1 × √n"},
        {"k": "Descente", "v": "Vz = gradient% × Vsol"},
    ],
    "R": [
        {"k": "1 NM", "v": "1,852 km"},
        {"k": "Règle 1:60", "v": "1° ≈ 1 NM à 60 NM"},
        {"k": "Semi-circulaire", "v": "Impairs 000–179° · Pairs 180–359°"},
        {"k": "Examen PPL", "v": "75 %/épreuve · 64 Q"},
        {"k": "Réserve VFR", "v": "30 min (jour, France)"},
        {"k": "Visibilité A", "v": "1500 m minimum"},
        {"k": "Triangle vitesses", "v": "TAS + vent → GS"},
    ],
}


def js_str(s):
    return json.dumps(s, ensure_ascii=False)


def emit_formula(f):
    parts = [f"id:{js_str(f['id'])}", f"m:{js_str(f['m'])}", f"cat:{js_str(f['cat'])}", f"title:{js_str(f['title'])}", f"formula:{js_str(f['formula'])}"]
    if f.get("units"):
        parts.append(f"units:{js_str(f['units'])}")
    if f.get("vars"):
        vars_js = ",".join(f"{{s:{js_str(v['s'])},d:{js_str(v['d'])}}}" for v in f["vars"])
        parts.append(f"vars:[{vars_js}]")
    if f.get("explain"):
        parts.append(f"explain:{js_str(f['explain'])}")
    if f.get("utility"):
        parts.append(f"utility:{js_str(f['utility'])}")
    if f.get("mnemonic"):
        parts.append(f"mnemonic:{js_str(f['mnemonic'])}")
    if f.get("examples"):
        parts.append(f"examples:[{','.join(js_str(e) for e in f['examples'])}]")
    if f.get("worked"):
        parts.append(f"worked:[{','.join(js_str(w) for w in f['worked'])}]")
    if f.get("quizRef"):
        parts.append(f"quizRef:{js_str(f['quizRef'])}")
    if f.get("calc"):
        parts.append(f"calc:{js_str(f['calc'])}")
    if f.get("prio"):
        parts.append(f"prio:{f['prio']}")
    if f.get("tags"):
        parts.append(f"tags:[{','.join(js_str(t) for t in f['tags'])}]")
    return "{" + ",".join(parts) + "}"


def main():
    bank = enrich_all(FORMULAS)
    counts = Counter(f["m"] for f in bank)
    calc_count = sum(1 for f in bank if f.get("calc"))
    prio3 = sum(1 for f in bank if f.get("prio", 2) >= 3)
    cats = len(set(f["cat"] for f in bank))
    meta = {
        "total": len(bank),
        "counts": dict(counts),
        "calcCount": calc_count,
        "examEssential": prio3,
        "categories": cats,
    }

    lines = [
        "// Banque de formules PPL / LAPL — généré par build_formulas.py",
        f"const FORMULA_META={json.dumps(meta, ensure_ascii=False)};",
        "const FORMULAS=[",
        ",\n".join(emit_formula(f) for f in bank),
        "];",
        f"const FORMULA_KEYWORDS={json.dumps(FORMULA_KEYWORDS, ensure_ascii=False)};",
        f"const MODULE_ESSENTIALS={json.dumps(MODULE_ESSENTIALS, ensure_ascii=False)};",
    ]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    with_util = sum(1 for f in bank if f.get("utility"))
    with_worked = sum(1 for f in bank if f.get("worked"))
    with_ex = sum(1 for f in bank if len(f.get("examples") or []) >= 2)
    print(f"Generated {OUT.name}: {len(bank)} formulas ({calc_count} calculators)")
    print(f"  utility: {with_util}/{len(bank)} · worked: {with_worked}/{len(bank)} · examples>=2: {with_ex}/{len(bank)}")


if __name__ == "__main__":
    main()
